name: Run Task

on:
  workflow_dispatch:
  schedule:
    - cron: '1/5 * * * *' 
env:
  UID_LIST: ${{ secrets.UID_LIST }}
  TO_LIST: ${{ secrets.TO_LIST }}
  MAIL_USR: ${{ secrets.MAIL_USR }}
  MAIL_AUTH: ${{ secrets.MAIL_AUTH }}
jobs:
  run-daily-task:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Script
      run: |
        python run.py --run_once
    - name: Create local changes
      run: |
        git add -A
    - name: Commit files
      run: |
        git config --local user.email "actions@users.noreply.github.com"
        git config --local user.name "Automated Publisher"
        timestamp=$(date -u)
        git commit -m "Automated publish: ${timestamp}" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
